name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-md:
    runs-on: ubuntu-24.04
    name: Lint Markdown content
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Markdown lint for README
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: ./.markdownlint.json
          args: ./README.md
  lint-editorconfig:
    runs-on: ubuntu-24.04
    name: Lint for editorconfig violations
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v2

  lint-markdown-toc:
    runs-on: ubuntu-24.04
    name: Lint for Table of Contents
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 16
      - run: npm install markdown-toc
      - run: ./node_modules/.bin/markdown-toc -i README.md
      - run: git diff --exit-code
